### PR TITLE
Fix async logging

### LINKED ISSUE #9: Fix async logger library

### PR DESCRIPTION
**Pull request by NathanEdg**
Fixed async logging by adding typed parameters to SpikeSystem

### CODE REVIEW

File: src/main/java/frc/robot/subsystems/vision/photon/Camera.java [hunk 1]
```diff
@@ -49,6 +54,12 @@ public EstimatedRobotPose getEstimatedRobotPose() {
         }
 
         return bestPose.orElse(null);
+
+        // var estimatedPose = poseEstimator.update(result).orElse(null);
```
Comment (bjmcternan) [inline src/main/java/frc/robot/subsystems/vision/photon/Camera.java]: If this code is not used we should delete it to avoid clutter.

File: src/main/java/frc/robot/subsystems/vision/photon/Camera.java [hunk 2]
```diff
@@ -34,6 +36,9 @@ public Camera(String id, Transform3d cameraToRobot) {
      */
     public EstimatedRobotPose getEstimatedRobotPose() {
         List<PhotonPipelineResult> results = photonCamera.getAllUnreadResults();
+        // PhotonPipelineResult result = photonCamera.getLatestResult();
+        // System.out.println("Pose from camera " + this.id + " " + result);
+        
         Optional<EstimatedRobotPose> bestPose = Optional.empty();
```
Comment (bjmcternan) [inline src/main/java/frc/robot/subsystems/vision/photon/Camera.java:40]: Let's add some comments about what this is doing. I'm assuming we're using "empty" and "NEGATIVE_INFINITY" because this is the first init and we do not have a pose yet. Is that right?

File: src/main/java/frc/robot/subsystems/vision/Vision.java [hunk 3]
```diff
@@ -2,32 +2,45 @@
...
     private final CommandSwerveDrivetrain drive;
 
     public Vision(CommandSwerveDrivetrain drive) {
-        super("Vision");
+        super("Vision", new VisionIO.VisionIOInputs());
+
         this.drive = drive;
-        this.photonCameras = new VisionIOPhotonCamera();
+
+        System.out.println("IO!!!!!!!!!!!!!!!!!!!!: " + io.estimatedRobotPoses + "\n\n\n\n");
```
Comment (bjmcternan) [inline src/main/java/frc/robot/subsystems/vision/Vision.java]: Let's remove the "!" and \n characters take time to print and the extra newlines will hide other important information. Just use the one \n and maybe a "IO -"

File: src/main/java/frc/robot/subsystems/vision/Vision.java [hunk 4]
```diff
@@ -2,32 +2,45 @@
...
     }
 
     @Override
     public void onPeriodic() {
+        int index = 0;
+        System.out.println("Camera sizes " + CameraManager.getCameras().size());
+
+        System.out.println("Poses " + io.estimatedRobotPoses.size());
         for (EstimatedRobotPose pose : io.estimatedRobotPoses) {
+            Logger.recordOutput("EstimatedPose/" + String.valueOf(index), pose.estimatedPose.toPose2d());
```
Comment (bjmcternan) [inline src/main/java/frc/robot/subsystems/vision/Vision.java]: Add some comments here too. What does this for loop update?

**Review by bjmcternan — CHANGES_REQUESTED** [review]
Some things to cleanup

File: src/main/java/frc/robot/subsystems/vision/photon/Camera.java (hunk 2 above)
Comment (NathanEdg) [reply src/main/java/frc/robot/subsystems/vision/photon/Camera.java:40]: It's so we can get the latest pose, so negative inf is the smallest time we can get so any time bigger will update the variable

File: src/main/java/frc/robot/subsystems/vision/Vision.java (hunk 3 above)
Comment (NathanEdg) [reply src/main/java/frc/robot/subsystems/vision/Vision.java]: Printing isn't needed anymore

File: src/main/java/frc/robot/subsystems/vision/Vision.java (hunk 4 above)
Comment (NathanEdg) [reply src/main/java/frc/robot/subsystems/vision/Vision.java]: Printed isn't needed anymore

File: src/main/java/frc/robot/subsystems/vision/photon/Camera.java (hunk 2 above)
Comment (bjmcternan) [reply src/main/java/frc/robot/subsystems/vision/photon/Camera.java:40]: That makes sense to me. Put that in as a comment so others who look at this code will also know that

**Review by bjmcternan — CHANGES_REQUESTED** [review]
one last fix

**Review by bjmcternan — APPROVED** [review]
Looks great thanks!

File: src/main/deploy/pathplanner/settings.json [hunk 5]
```diff
@@ -0,0 +1,32 @@
...
+  "frModuleX": 0.273,
+  "frModuleY": -0.273,
+  "blModuleX": -0.273,
+  "blModuleY": 0.273,
+  "brModuleX": -0.273,
+  "brModuleY": -0.273,
+  "bumperOffsetX": 0.0,
+  "bumperOffsetY": 0.0,
+  "robotFeatures": []
+}
```
Comment (afranchuk) [inline src/main/deploy/pathplanner/settings.json:32]: Why is this file here? It doesn't seem related to this PR. Maybe it should have been in the init codebase PR?

Though looking through the rest of this PR, there's quite a bit more than just async logging changes. Maybe rename the PR, or update the description? It's great for that information to reflect the content so that a reviewer knows what to expect, but also useful for traceability if we need to find a PR related to changes.

File: src/main/java/frc/lib/subsystem/SpikeSystem.java [hunk 6]
```diff
@@ -4,27 +4,30 @@
...
 
     protected abstract Runnable setupDataRefresher();
 
-    protected <I extends BaseInputClass, T extends BaseIO<I> & IORefresher> Runnable useAsyncDataRefresher(
-            I inputs, T baseIO
+    protected <T extends BaseIO<I> & IORefresher> Runnable useAsyncDataRefresher(
+        T baseIO
     ) {
-        DataUtils.createDataLogger(inputs, baseIO);
+        System.out.println("Inputs: " + io);
```
Comment (afranchuk) [inline src/main/java/frc/lib/subsystem/SpikeSystem.java]: Remove debug code? I'm not sure this is useful to keep printing. It's best not to clog output for when we do need to find pertinent information there.

File: src/main/java/frc/lib/SubsystemDataProcessor.java [hunk 7]
```diff
@@ -29,19 +29,26 @@ public static void createAndStartSubsystemDataProcessor(
...
+            IODataRefresher... refreshers) {                 
         this.dataReaderAndLogger = dataReaderAndLogger;
         IODataRefreshers = List.of(refreshers);
     }
 
+    @Override
     public void run() {
         while (true) {
             timestamp = System.currentTimeMillis();
+            System.out.println(IODataRefreshers.size());
```
Comment (afranchuk) [inline src/main/java/frc/lib/SubsystemDataProcessor.java]: Remove debug code

File: src/main/java/frc/robot/subsystems/vision/photon/CameraManager.java [hunk 8]
```diff
@@ -16,6 +24,36 @@ public static List<Camera> getCameras() {
...
+                    Inches.of(-29.5/2),
+                    Inches.of(9.25),
+                    new Rotation3d(
+                        Degrees.of(-90),
+                        Degrees.of(0),
+                        Degrees.of(0)
+                    )
+                 )
+            )
+        );
```
Comment (afranchuk) [inline src/main/java/frc/robot/subsystems/vision/photon/CameraManager.java:57]: These changes close #8.

**Review by afranchuk — DISMISSED** [review]
Functionally, this looks fine (aside from some extraneous `System.out.println`). I'm requesting changes mainly so the PR name/description mentions more than just the async logging, and mentions that #8 will be closed.

File: src/main/java/frc/lib/subsystem/SpikeSystem.java (hunk 6 above)
Comment (bjmcternan) [reply src/main/java/frc/lib/subsystem/SpikeSystem.java]: These printouts are likely OK provided they aren't too large. I'm OK with it for now

File: src/main/java/frc/lib/SubsystemDataProcessor.java (hunk 7 above)
Comment (bjmcternan) [reply src/main/java/frc/lib/SubsystemDataProcessor.java]: See https://github.com/Team293/Rebuilt/pull/16#discussion_r2783915210

File: src/main/deploy/pathplanner/settings.json (hunk 5 above)
Comment (NathanEdg) [reply src/main/deploy/pathplanner/settings.json:32]: I'm not too sure either, probably from testing or whatnot, though I'd like to keep it here

**Comment by NathanEdg** [comment]
@afranchuk @PillageDev are you able to review this to allow for merge

**Review by PillageDev — APPROVED** [review]

**Review by maxim-kudryashov — APPROVED** [review]
